// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTPr1Z81L_rqSRDLK0AdL7t8E_HhUySd4',
    appId: '1:786326787465:web:e34a1f8077099c1c997d58',
    messagingSenderId: '786326787465',
    projectId: 'gmsg-de9a0',
    authDomain: 'gmsg-de9a0.firebaseapp.com',
    databaseURL: 'https://gmsg-de9a0-default-rtdb.firebaseio.com',
    storageBucket: 'gmsg-de9a0.appspot.com',
    measurementId: 'G-13L81DCV8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-RaZUtY2_YLHsBTx5FYgpt4I-CGwp6c',
    appId: '1:786326787465:android:676788ab2b9d459d997d58',
    messagingSenderId: '786326787465',
    projectId: 'gmsg-de9a0',
    databaseURL: 'https://gmsg-de9a0-default-rtdb.firebaseio.com',
    storageBucket: 'gmsg-de9a0.appspot.com',
  );
}
